steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run:
        sudo apt-get install -y valgrind cppcheck g++-9 cmake
    - name: make
      run: g++ -Wall -Wextra -pedantic -std=c++17 *.cpp -o main -g
    - name: cppcheck
      run:
        cppcheck --enable=all .
    - name: valgrind
      run:
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./main
        
        
        
