name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run:
        sudo apt-get install -y valgrind cppcheck g++-9 cmake
    - name: configure
      run:
        cmake .
    - name: make
      run: make
    - name: cppcheck
      run:
        cppcheck --enable=all -i cmake-build-debug/ .
    - name: valgrind
      run:
        valgrind -v --leak-check=full --show-leak-kinds=all --track-origins=yes ./$(grep "add_executable" CMakeLists.txt | awk '{print $1}' | sed s/.*\(//)
